import { ShieldCheck } from 'lucide-react';

interface Section {
  title: string;
  body: React.ReactNode;
}

const SECTIONS: Section[] = [
  {
    title: '1. Information We Collect',
    body: (
      <>
        <p>We collect the information you give us directly, and some information generated by using the app:</p>
        <ul className="mt-2 list-disc space-y-1 pl-5">
          <li>Account details — name, mobile number, email address, and gender (optional).</li>
          <li>Delivery addresses, including location coordinates, so we can route your order correctly.</li>
          <li>Order history, cart contents, and wallet transactions.</li>
          <li>Product ratings and reviews you choose to submit.</li>
          <li>A device push-notification token, used to send you order updates.</li>
          <li>Basic technical data such as IP address and device/browser type, for security and troubleshooting.</li>
        </ul>
      </>
    ),
  },
  {
    title: '2. How We Use Your Information',
    body: (
      <ul className="list-disc space-y-1 pl-5">
        <li>To process and deliver your orders, including assigning a picker and delivery partner.</li>
        <li>To verify your identity via one-time password (OTP) sent to your mobile number.</li>
        <li>To send order-status notifications, offers, and service updates.</li>
        <li>To process payments and refunds, and to maintain your Grovio Wallet balance.</li>
        <li>To respond to support tickets you raise with us.</li>
        <li>To detect and prevent fraud, abuse, or violations of our Terms &amp; Conditions.</li>
      </ul>
    ),
  },
  {
    title: '3. Who We Share It With',
    body: (
      <>
        <p>We do not sell your personal data. We share the minimum necessary information with:</p>
        <ul className="mt-2 list-disc space-y-1 pl-5">
          <li>The picker and delivery partner fulfilling your order — your name, address, and phone number, so your order can reach you.</li>
          <li>Razorpay, our payment processor, to complete online payments. We do not store your full card or bank details ourselves.</li>
          <li>Law enforcement or regulators, only when legally required to do so.</li>
        </ul>
      </>
    ),
  },
  {
    title: '4. Your Delivery PIN and Order Security',
    body: (
      <p>
        The one-time delivery PIN generated for your order is shown only to you inside the app. Grovio staff will never call and ask for
        this PIN outside of the actual doorstep handover — do not share it with anyone claiming to need it over the phone.
      </p>
    ),
  },
  {
    title: '5. Data Retention',
    body: (
      <p>
        We retain your account and order data for as long as your account is active, and for a reasonable period afterward to meet legal,
        tax, and accounting obligations. You may request account deletion at any time via Help &amp; Support; some order records may be
        retained where required by law.
      </p>
    ),
  },
  {
    title: '6. Your Choices',
    body: (
      <ul className="list-disc space-y-1 pl-5">
        <li>You can view and update your name and email anytime from your Profile page.</li>
        <li>You can add, edit, or remove saved delivery addresses at any time.</li>
        <li>You can disable push notifications from your device settings.</li>
        <li>You can request a copy of your data, or its deletion, by raising a ticket via Help &amp; Support.</li>
      </ul>
    ),
  },
  {
    title: '7. Security',
    body: (
      <p>
        We use industry-standard measures — including encrypted network connections and access-controlled systems — to protect your data.
        No method of transmission or storage is 100% secure, and we continuously work to improve our safeguards.
      </p>
    ),
  },
  {
    title: '8. Children’s Privacy',
    body: (
      <p>
        Grovio is not directed at children under 18. We do not knowingly collect personal information from anyone under this age. If you
        believe a minor has provided us with personal data, please contact us and we will remove it.
      </p>
    ),
  },
  {
    title: '9. Changes to This Policy',
    body: (
      <p>
        We may update this Privacy Policy periodically. Material changes will be highlighted in the app. Continuing to use Grovio after an
        update means you accept the revised policy.
      </p>
    ),
  },
  {
    title: '10. Contact Us',
    body: (
      <p>
        For any privacy-related questions or requests, email us at{' '}
        <a href="mailto:support@grovio.com" className="font-medium text-brand-700 hover:underline">
          support@grovio.com
        </a>{' '}
        or raise a ticket via Help &amp; Support.
      </p>
    ),
  },
];

export default function PrivacyPolicyPage() {
  return (
    <div className="mx-auto max-w-3xl">
      <div className="mb-6 flex items-center gap-3">
        <div className="flex h-11 w-11 items-center justify-center rounded-full bg-brand-100 text-brand-700">
          <ShieldCheck size={20} />
        </div>
        <div>
          <h1 className="text-xl font-bold text-gray-900">Privacy Policy</h1>
          <p className="text-sm text-gray-500">Last updated: January 2026</p>
        </div>
      </div>

      <div className="rounded-xl border border-gray-200 bg-white p-5 flex flex-col gap-6">
        {SECTIONS.map((section) => (
          <section key={section.title}>
            <h2 className="mb-1.5 text-sm font-semibold text-gray-900">{section.title}</h2>
            <div className="text-sm leading-relaxed text-gray-500">{section.body}</div>
          </section>
        ))}
      </div>
    </div>
  );
}
