module.exports = {
  User: require('./user.model'),
  Otp: require('./otp.model'),
  Store: require('./store.model'),
  DeliveryProfile: require('./deliveryProfile.model'),
  PickerProfile: require('./pickerProfile.model'),
  Category: require('./category.model'),
  Product: require('./product.model'),
  Address: require('./address.model'),
  Cart: require('./cart.model'),
  Wishlist: require('./wishlist.model'),
  Order: require('./order.model'),
  Payment: require('./payment.model'),
  Refund: require('./refund.model'),
  Wallet: require('./wallet.model'),
  WalletTransaction: require('./walletTransaction.model'),
  Coupon: require('./coupon.model'),
  CouponUsage: require('./couponUsage.model'),
  Banner: require('./banner.model'),
  Review: require('./review.model'),
  Notification: require('./notification.model'),
  SupportTicket: require('./supportTicket.model'),
  Setting: require('./setting.model'),
  Settlement: require('./settlement.model'),
  AdminActivityLog: require('./adminActivityLog.model'),
  RefreshToken: require('./refreshToken.model'),
  UserDevice: require('./userDevice.model'),
};
