import { Table, Typography, Button, Popconfirm } from 'antd';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { fetchSettlements, markSettlementPaid } from '../api/settlements';
import type { Settlement, User } from '../types';
import { usePageState } from '../hooks/usePageState';
import StatusTag from '../components/StatusTag';
import { formatCurrency, formatDateTime } from '../utils/format';

// Settlements (picker/delivery payouts) are generated by the backend, not from this page —
// there's no admin "generate" endpoint. This page only lists them and marks payouts as paid.
export default function SettlementsPage() {
  const { page, pageSize, onChange } = usePageState();
  const queryClient = useQueryClient();

  const { data, isLoading } = useQuery({
    queryKey: ['settlements', page, pageSize],
    queryFn: () => fetchSettlements({ page, limit: pageSize }),
  });

  const payMutation = useMutation({
    mutationFn: markSettlementPaid,
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['settlements'] });
    },
  });

  return (
    <div>
      <Typography.Title level={3} style={{ margin: 0, marginBottom: 16 }}>
        Settlements
      </Typography.Title>

      <Table<Settlement>
        rowKey="_id"
        loading={isLoading}
        dataSource={data?.items}
        pagination={{ current: page, pageSize, total: data?.meta.totalItems, onChange, showSizeChanger: true }}
        columns={[
          { title: 'Payee', render: (_, r) => (typeof r.payeeUser === 'object' ? (r.payeeUser as User).name : r.payeeUser) },
          { title: 'Role', dataIndex: 'payeeRole' },
          { title: 'Period', render: (_, r) => `${formatDateTime(r.periodFrom)} → ${formatDateTime(r.periodTo)}` },
          { title: 'Orders', dataIndex: 'orderCount' },
          { title: 'Gross', render: (_, r) => formatCurrency(r.grossAmount) },
          { title: 'Commission', render: (_, r) => formatCurrency(r.commissionAmount) },
          { title: 'Payout', render: (_, r) => formatCurrency(r.payoutAmount) },
          { title: 'Status', render: (_, r) => <StatusTag status={r.status} /> },
          {
            title: 'Actions',
            render: (_, r) =>
              r.status === 'pending' ? (
                <Popconfirm title="Mark this settlement as paid?" onConfirm={() => payMutation.mutate(r._id)}>
                  <Button size="small" type="primary">
                    Mark Paid
                  </Button>
                </Popconfirm>
              ) : (
                '—'
              ),
          },
        ]}
      />
    </div>
  );
}
