// Initial content for the admin-editable static pages (see models/contentPage.model.js),
// carried over from the hardcoded copy that used to live directly in customer-web's
// AboutUsPage/PrivacyPolicyPage/TermsPage components.
const DEFAULT_CONTENT_PAGES = [
  {
    slug: 'about-us',
    title: 'About Us',
    content: `
<h2>Who We Are</h2>
<p>Grovio is a quick-commerce grocery platform built to get fresh fruits, vegetables, dairy, and everyday household essentials to your doorstep in minutes, not hours. We partner with local dark stores across your city so your order comes from a store near you, packed by a real person and delivered by a real person — not a warehouse three states away.</p>

<h2>Our Mission</h2>
<p>We believe grocery shopping shouldn't eat into your day. Our mission is simple: make it effortless to get what you need, when you need it, at a fair price — without compromising on freshness or service.</p>

<h2>How Grovio Works</h2>
<ul>
<li>You browse products from your nearest Grovio store and place an order.</li>
<li>The store accepts your order and a picker gets to work picking and packing it.</li>
<li>A delivery partner collects the packed order and heads your way.</li>
<li>You confirm delivery with a one-time PIN shown right in the app — simple, and secure.</li>
</ul>

<h2>Why Choose Grovio</h2>
<ul>
<li>Fast delivery, sourced from a store close to you.</li>
<li>Fresh produce and everyday essentials, checked before packing.</li>
<li>Transparent pricing with no hidden charges at checkout.</li>
<li>Secure payments — Cash on Delivery, UPI, cards, and netbanking.</li>
<li>Real-time order tracking from picking to delivery.</li>
</ul>

<h2>Get in Touch</h2>
<p>Have a question, feedback, or a partnership idea? We'd love to hear from you at <a href="mailto:support@grovio.com">support@grovio.com</a> or raise a ticket via Help &amp; Support.</p>
`.trim(),
  },
  {
    slug: 'privacy-policy',
    title: 'Privacy Policy',
    content: `
<h2>1. Information We Collect</h2>
<p>We collect the information you give us directly, and some information generated by using the app:</p>
<ul>
<li>Account details — name, mobile number, email address, and gender (optional).</li>
<li>Delivery addresses, including location coordinates, so we can route your order correctly.</li>
<li>Order history, cart contents, and wallet transactions.</li>
<li>Product ratings and reviews you choose to submit.</li>
<li>A device push-notification token, used to send you order updates.</li>
<li>Basic technical data such as IP address and device/browser type, for security and troubleshooting.</li>
</ul>

<h2>2. How We Use Your Information</h2>
<ul>
<li>To process and deliver your orders, including assigning a picker and delivery partner.</li>
<li>To verify your identity via one-time password (OTP) sent to your mobile number.</li>
<li>To send order-status notifications, offers, and service updates.</li>
<li>To process payments and refunds, and to maintain your Grovio Wallet balance.</li>
<li>To respond to support tickets you raise with us.</li>
<li>To detect and prevent fraud, abuse, or violations of our Terms &amp; Conditions.</li>
</ul>

<h2>3. Who We Share It With</h2>
<p>We do not sell your personal data. We share the minimum necessary information with:</p>
<ul>
<li>The picker and delivery partner fulfilling your order — your name, address, and phone number, so your order can reach you.</li>
<li>Razorpay, our payment processor, to complete online payments. We do not store your full card or bank details ourselves.</li>
<li>Law enforcement or regulators, only when legally required to do so.</li>
</ul>

<h2>4. Your Delivery PIN and Order Security</h2>
<p>The one-time delivery PIN generated for your order is shown only to you inside the app. Grovio staff will never call and ask for this PIN outside of the actual doorstep handover — do not share it with anyone claiming to need it over the phone.</p>

<h2>5. Data Retention</h2>
<p>We retain your account and order data for as long as your account is active, and for a reasonable period afterward to meet legal, tax, and accounting obligations. You may request account deletion at any time via Help &amp; Support; some order records may be retained where required by law.</p>

<h2>6. Your Choices</h2>
<ul>
<li>You can view and update your name and email anytime from your Profile page.</li>
<li>You can add, edit, or remove saved delivery addresses at any time.</li>
<li>You can disable push notifications from your device settings.</li>
<li>You can request a copy of your data, or its deletion, by raising a ticket via Help &amp; Support.</li>
</ul>

<h2>7. Security</h2>
<p>We use industry-standard measures — including encrypted network connections and access-controlled systems — to protect your data. No method of transmission or storage is 100% secure, and we continuously work to improve our safeguards.</p>

<h2>8. Children's Privacy</h2>
<p>Grovio is not directed at children under 18. We do not knowingly collect personal information from anyone under this age. If you believe a minor has provided us with personal data, please contact us and we will remove it.</p>

<h2>9. Changes to This Policy</h2>
<p>We may update this Privacy Policy periodically. Material changes will be highlighted in the app. Continuing to use Grovio after an update means you accept the revised policy.</p>

<h2>10. Contact Us</h2>
<p>For any privacy-related questions or requests, email us at <a href="mailto:support@grovio.com">support@grovio.com</a> or raise a ticket via Help &amp; Support.</p>
`.trim(),
  },
  {
    slug: 'terms-and-conditions',
    title: 'Terms & Conditions',
    content: `
<h2>1. Acceptance of Terms</h2>
<p>By creating a Grovio account or placing an order through our app or website, you agree to be bound by these Terms &amp; Conditions. If you do not agree with any part of these terms, please do not use the Grovio service.</p>

<h2>2. Who Can Use Grovio</h2>
<p>Grovio is available to individuals who can form a legally binding contract under applicable law and who provide accurate registration details. You are responsible for maintaining the confidentiality of your account and for all activity under it, including the OTP sent to your registered mobile number.</p>

<h2>3. Orders and Availability</h2>
<p>All products listed on Grovio are subject to availability at the fulfilling store. We reserve the right to limit quantities, refuse or cancel any order — including after payment — if a product turns out to be unavailable, mispriced, or if we suspect fraudulent or abusive activity.</p>
<p>If we cancel an order you have already paid for, the amount is credited to your Grovio Wallet. See our Returns &amp; Refunds policy for details.</p>

<h2>4. Pricing and Payment</h2>
<p>Prices shown at checkout are final and include all applicable taxes and delivery fees unless stated otherwise. We accept Cash on Delivery, online payment via Razorpay (cards, UPI, netbanking, and wallets), and your Grovio Wallet balance. By choosing an online payment method, you authorize us and our payment partner to process the transaction.</p>

<h2>5. Delivery</h2>
<p>Delivery timelines shown in the app are estimates, not guarantees, and can be affected by weather, traffic, or store readiness. A one-time PIN is generated once a delivery partner is assigned to your order — you must share this PIN with the delivery partner to confirm receipt of your order. Do not share it before the delivery partner has arrived with your items.</p>

<h2>6. Grovio Wallet</h2>
<p>The Grovio Wallet is a store-of-value feature used to hold refunds and credits within your account. Wallet balance has no cash withdrawal value, cannot be transferred to another user, and can only be redeemed against future Grovio orders.</p>

<h2>7. User Conduct</h2>
<p>You agree not to misuse the platform — including placing fraudulent orders, abusing promotional coupons, providing false delivery addresses, or being abusive toward our pickers or delivery partners. We reserve the right to suspend or terminate accounts that violate these terms.</p>

<h2>8. Reviews and Content</h2>
<p>Any product ratings or reviews you submit must be honest, based on genuine experience, and free of offensive or unlawful content. We may remove content that violates this at our discretion.</p>

<h2>9. Limitation of Liability</h2>
<p>Grovio is provided on an "as is" basis. To the maximum extent permitted by law, we are not liable for indirect or consequential losses arising from delays, stock unavailability, or service interruptions. Our total liability for any claim is limited to the value of the order giving rise to that claim.</p>

<h2>10. Changes to These Terms</h2>
<p>We may update these Terms &amp; Conditions from time to time to reflect changes in our service or legal requirements. Continued use of Grovio after an update constitutes acceptance of the revised terms.</p>

<h2>11. Contact Us</h2>
<p>Questions about these terms can be sent to <a href="mailto:support@grovio.com">support@grovio.com</a> or raised via our Help &amp; Support page.</p>
`.trim(),
  },
];

module.exports = { DEFAULT_CONTENT_PAGES };
